config/routes.rb
TAMC::Application.routes.draw do
  resources :system_settings do
    get :getAppVersion, :on => :collection
  end

  resources :cold_storages

  resources :gunnay_tare_weights

  resources :bag_names

  resources :sub_lots

  resources :market_charges

  resources :segments

  resources :gunny_details

  resources :sale_bill_components

  resources :salebills

  resources :bag_weights

  resources :weighment_bag_weights

  resources :bids

  resources :weighments do
    get :get_lot_details, :on => :collection
    get :create_weighment, :on => :collection
    post :update_weighment, :on => :collection
    get :edit_weighment, :on => :collection
    post :updated_weighment, :on => :collection
  end

  resources :lots do
    get :bidding_lots_list, :on => :collection
    get :add_bid, :on => :collection
    post :update_bid, :on => :collection
    get :close_bidding, :on => :collection
    get :show_entry_ticket, :on => :collection
    get :wayment_done_lots, :on => :collection
    get :make_inactive, :on => :collection
    get :takparty_receipt, :on => :collection
    get :update_data, :on => :collection
    get :modify_lot, :on => :collection
    get :modify_lot, :on => :collection
    post :lot_updated, :on => :collection
    get :lots_information, :on => :collection
    get :arrivedLotsInformation, :on => :collection
    get :pendingLotsInformation, :on => :collection
    get :returnedLotsInformation, :on => :collection
    get :day_wise_summary, :on => :collection
    get :day_wise_summary1, :on => :collection
    post :nrBidUpdate, :on => :collection
    post :nrBidUpdate1, :on => :collection
    get :nrlotBidding, :on => :collection
    get :nrlotBidding1, :on => :collection
    get :market_fee_details, :on => :collection
    get :makeDelete, :on => :collection
    get :add_remarks, :on => :collection
    post :save_remarks, :on => :collection
    get :detailsOfFee, :on => :collection
    get :getLotNumbers, :on => :collection
    get :getlotInformation, :on => :collection
  end

  resources :gate_entries do
    get :show_lots, :on => :collection
    get :create_gate_pass, :on => :collection
    post :generate_gate_entries, :on => :collection
    get :get_farmers, :on => :collection
    get :generate_gate_entry, :on => :collection
    get :set_farmer_details, :on => :collection
  end

  resources :farmers do
    post :list_of_vehicle_types, :on => :collection
    post :list_of_uoms, :on => :collection
    post :list_of_bag_types, :on => :collection
    post :list_of_commodities, :on => :collection
    post :list_of_farmer, :on => :collection

    post :stateList, :on => :collection
    post :districtsList, :on => :collection
    post :mandalsList, :on => :collection
    post :CityList, :on => :collection
    post :create_new_farmer, :on => :collection
    get :dashboard, :on => :collection
    get :dashboard1, :on => :collection
    get :amcwise_farmer_list, :on => :collection

  end

  resources :fee_components

  resources :fee_categories do
    get :listFeeCategoryForAutoSaleModel, :on => :collection
    get :listFeeComponentMstDtlAutoSaleModel, :on => :collection
  end

  resources :commodities

  resources :bag_types

  resources :unit_of_measurements

  resources :vehicle_types

  resources :users do
    get :create_user, :on => :collection
    post :update_user, :on => :collection
    get :agents_list, :on => :collection
    get :employee_list, :on => :collection
    get :create_agent, :on => :collection
    post :update_agent, :on => :collection
    get :create_employee, :on => :collection
    post :update_employee, :on => :collection
    post :user_verification, :on => :collection
    post :agentList, :on => :collection
    get :getMasterDataHW, :on => :collection
    get :cold_storages_update, :on => :collection
    get :getCaNames, :on => :collection
    get :inactive_user, :on => :collection
    get :active_user, :on => :collection
  end

  resources :user_roles

  resources :villages do
    get :mandal_wise_villages, :on => :collection
  end

  resources :mandals do
    get :districtwise_mandals_list, :on => :collection
  end

  resources :districts do
    get :statewise_district_list, :on => :collection
  end

  resources :states do

  end

  resources :amcs do
    get :all_amc_list, :on => :collection
    get :select_amc, :on => :collection
  end

  resources :user_sessions do
    get :new, :on => :collection
  end

  match 'logout', :controller => 'user_sessions', :action => 'destroy'
  match 'login', :controller => 'user_sessions', :action => 'new'

  root :to => 'user_sessions#new'

end

app/models/unit_of_measurement.rb
class UnitOfMeasurement < ActiveRecord::Base
  attr_accessible :amc_id, :description, :is_active, :unit_name
end

app/controllers/unit_of_measurements_controller.rb
class UnitOfMeasurementsController < ApplicationController
  # GET /unit_of_measurements
  # GET /unit_of_measurements.json
  def index
    if current_user.present? && current_user.amc_id.present?
      @unit_of_measurements = UnitOfMeasurement.where("amc_id =?",current_user.amc_id)
    else
      @unit_of_measurements = UnitOfMeasurement.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unit_of_measurements }
    end
  end

  # GET /unit_of_measurements/1
  # GET /unit_of_measurements/1.json
  def show
    @unit_of_measurement = UnitOfMeasurement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit_of_measurement }
    end
  end

  # GET /unit_of_measurements/new
  # GET /unit_of_measurements/new.json
  def new
    @unit_of_measurement = UnitOfMeasurement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit_of_measurement }
    end
  end

  # GET /unit_of_measurements/1/edit
  def edit
    @unit_of_measurement = UnitOfMeasurement.find(params[:id])
  end

  # POST /unit_of_measurements
  # POST /unit_of_measurements.json
  def create
    @unit_of_measurement = UnitOfMeasurement.new(params[:unit_of_measurement])

    respond_to do |format|
      if @unit_of_measurement.save
        format.html { redirect_to '/unit_of_measurements', notice: 'Unit of measurement was successfully created.' }
        format.json { render json: @unit_of_measurement, status: :created, location: @unit_of_measurement }
      else
        format.html { render action: "new" }
        format.json { render json: @unit_of_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unit_of_measurements/1
  # PUT /unit_of_measurements/1.json
  def update
    @unit_of_measurement = UnitOfMeasurement.find(params[:id])

    respond_to do |format|
      if @unit_of_measurement.update_attributes(params[:unit_of_measurement])
        format.html { redirect_to '/unit_of_measurements', notice: 'Unit of measurement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit_of_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_of_measurements/1
  # DELETE /unit_of_measurements/1.json
  def destroy
    @unit_of_measurement = UnitOfMeasurement.find(params[:id])
    @unit_of_measurement.destroy

    respond_to do |format|
      format.html { redirect_to unit_of_measurements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/unit_of_measurements_helper.rb
module UnitOfMeasurementsHelper
end

app/views/unit_of_measurements/_form.html.erb
<%= form_for(@unit_of_measurement) do |f| %>
  <% if @unit_of_measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit_of_measurement.errors.count, "error") %> prohibited this unit_of_measurement from being
        saved:</h2>

      <ul>
        <% @unit_of_measurement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :unit_name, :class => 'label-tag-style', :style => "text-transform: capitalize;color:black" %>
        <%= f.text_field :unit_name, :class => 'form-control', :placeholder => 'Unit Name ', :required => true %>
      </div>
      <div class="field">
        <%= f.label :description, :class => 'label-tag-style', :style => "text-transform: capitalize;color:black" %>
        <%= f.text_area :description, :class => 'form-control', :placeholder => 'Description ', :size => '10X20' %>
      </div>
      <%= f.hidden_field :amc_id, :value => current_user.amc_id %>
      <div class="field">
        <%= f.label :is_active %><br/>
        <%= f.check_box :is_active %>
      </div>
      <div class="actions">
        <%= f.submit(:class => 'btn btn-success btn-md') %>
      </div>
    </div>
  </div>
<% end %>

app/views/unit_of_measurements/edit.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('Edit Unit Of Measurement') %></div>

    <div class="col-sm-6 text-right"><%= link_to 'Back', unit_of_measurements_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>

  <%= render 'form' %>
</div>

app/views/unit_of_measurements/index.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('units Of Measurements') %></div>
    <div class="col-sm-6 text-right"><%= link_to 'New Unit Of Measurement', new_unit_of_measurement_path, :class => 'btn btn-success', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>
  <table class="table table-bordered">
    <tr class="tr_style">
      <th>Unit name</th>
      <th>Description</th>
      <th>Is active</th>
      <% if current_user.present? && current_user.is_admin %>
      <th></th>
      <th></th>
      <% end %>
    </tr>

    <% @unit_of_measurements.each do |unit_of_measurement| %>
      <tr>
        <td><%= unit_of_measurement.unit_name %></td>
        <td><%= unit_of_measurement.description %></td>
        <td><%= unit_of_measurement.is_active %></td>
        <% if current_user.present? && current_user.is_admin %>
        <td><%= link_to 'Edit', edit_unit_of_measurement_path(unit_of_measurement) %></td>
        <td><%= link_to 'Destroy', unit_of_measurement, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

</div>

app/views/unit_of_measurements/new.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('New Unit Of Measurement') %></div>

    <div class="col-sm-6 text-right"><%= link_to 'Back', unit_of_measurements_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>

  <%= render 'form' %>
</div>