config/routes.rb
TAMC::Application.routes.draw do
  resources :system_settings do
    get :getAppVersion, :on => :collection
  end

  resources :cold_storages

  resources :gunnay_tare_weights

  resources :bag_names

  resources :sub_lots

  resources :market_charges

  resources :segments

  resources :gunny_details

  resources :sale_bill_components

  resources :salebills

  resources :bag_weights

  resources :weighment_bag_weights

  resources :bids

  resources :weighments do
    get :get_lot_details, :on => :collection
    get :create_weighment, :on => :collection
    post :update_weighment, :on => :collection
    get :edit_weighment, :on => :collection
    post :updated_weighment, :on => :collection
  end

  resources :lots do
    get :bidding_lots_list, :on => :collection
    get :add_bid, :on => :collection
    post :update_bid, :on => :collection
    get :close_bidding, :on => :collection
    get :show_entry_ticket, :on => :collection
    get :wayment_done_lots, :on => :collection
    get :make_inactive, :on => :collection
    get :takparty_receipt, :on => :collection
    get :update_data, :on => :collection
    get :modify_lot, :on => :collection
    get :modify_lot, :on => :collection
    post :lot_updated, :on => :collection
    get :lots_information, :on => :collection
    get :arrivedLotsInformation, :on => :collection
    get :pendingLotsInformation, :on => :collection
    get :returnedLotsInformation, :on => :collection
    get :day_wise_summary, :on => :collection
    get :day_wise_summary1, :on => :collection
    post :nrBidUpdate, :on => :collection
    post :nrBidUpdate1, :on => :collection
    get :nrlotBidding, :on => :collection
    get :nrlotBidding1, :on => :collection
    get :market_fee_details, :on => :collection
    get :makeDelete, :on => :collection
    get :add_remarks, :on => :collection
    post :save_remarks, :on => :collection
    get :detailsOfFee, :on => :collection
    get :getLotNumbers, :on => :collection
    get :getlotInformation, :on => :collection
  end

  resources :gate_entries do
    get :show_lots, :on => :collection
    get :create_gate_pass, :on => :collection
    post :generate_gate_entries, :on => :collection
    get :get_farmers, :on => :collection
    get :generate_gate_entry, :on => :collection
    get :set_farmer_details, :on => :collection
  end

  resources :farmers do
    post :list_of_vehicle_types, :on => :collection
    post :list_of_uoms, :on => :collection
    post :list_of_bag_types, :on => :collection
    post :list_of_commodities, :on => :collection
    post :list_of_farmer, :on => :collection

    post :stateList, :on => :collection
    post :districtsList, :on => :collection
    post :mandalsList, :on => :collection
    post :CityList, :on => :collection
    post :create_new_farmer, :on => :collection
    get :dashboard, :on => :collection
    get :dashboard1, :on => :collection
    get :amcwise_farmer_list, :on => :collection

  end

  resources :fee_components

  resources :fee_categories do
    get :listFeeCategoryForAutoSaleModel, :on => :collection
    get :listFeeComponentMstDtlAutoSaleModel, :on => :collection
  end

  resources :commodities

  resources :bag_types

  resources :unit_of_measurements

  resources :vehicle_types

  resources :users do
    get :create_user, :on => :collection
    post :update_user, :on => :collection
    get :agents_list, :on => :collection
    get :employee_list, :on => :collection
    get :create_agent, :on => :collection
    post :update_agent, :on => :collection
    get :create_employee, :on => :collection
    post :update_employee, :on => :collection
    post :user_verification, :on => :collection
    post :agentList, :on => :collection
    get :getMasterDataHW, :on => :collection
    get :cold_storages_update, :on => :collection
    get :getCaNames, :on => :collection
    get :inactive_user, :on => :collection
    get :active_user, :on => :collection
  end

  resources :user_roles

  resources :villages do
    get :mandal_wise_villages, :on => :collection
  end

  resources :mandals do
    get :districtwise_mandals_list, :on => :collection
  end

  resources :districts do
    get :statewise_district_list, :on => :collection
  end

  resources :states do

  end

  resources :amcs do
    get :all_amc_list, :on => :collection
    get :select_amc, :on => :collection
  end

  resources :user_sessions do
    get :new, :on => :collection
  end

  match 'logout', :controller => 'user_sessions', :action => 'destroy'
  match 'login', :controller => 'user_sessions', :action => 'new'

  root :to => 'user_sessions#new'

end

app/models/mandal.rb
class Mandal < ActiveRecord::Base
  attr_accessible :code, :district_id, :is_active, :name, :state_id


  def self.get_mandals(prefix, amc)
    vendor_names = where("(name like ? and state_id= ?)", "%#{prefix}%", amc).order('name ASC')
  end

end

app/controllers/mandals_controller.rb
class MandalsController < ApplicationController
  # GET /mandals
  # GET /mandals.json
  filter_resource_access
  filter_access_to :districtwise_mandals_list, :attribute_check => false

  include FarmersHelper
  include StatesHelper
  include ApplicationHelper

  def index
    @mandals = Mandal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mandals }
    end
  end

  # GET /mandals/1
  # GET /mandals/1.json
  def show
    @mandal = Mandal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mandal }
    end
  end

  # GET /mandals/new
  # GET /mandals/new.json
  def new
    @mandal = Mandal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mandal }
    end
  end

  # GET /mandals/1/edit
  def edit
    @mandal = Mandal.find(params[:id])
  end

  # POST /mandals
  # POST /mandals.json
  def create
    @mandal = Mandal.new(params[:mandal])

    respond_to do |format|
      if @mandal.save
        format.html { redirect_to '/mandals', notice: 'Mandal was successfully created.' }
        format.json { render json: @mandal, status: :created, location: @mandal }
      else
        format.html { render action: "new" }
        format.json { render json: @mandal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mandals/1
  # PUT /mandals/1.json
  def update
    @mandal = Mandal.find(params[:id])

    respond_to do |format|
      if @mandal.update_attributes(params[:mandal])
        format.html { redirect_to '/mandals', notice: 'Mandal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mandal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mandals/1
  # DELETE /mandals/1.json
  def destroy
    @mandal = Mandal.find(params[:id])
    @mandal.destroy

    respond_to do |format|
      format.html { redirect_to mandals_url }
      format.json { head :no_content }
    end
  end

  def districtwise_mandals_list
    mandals = Mandal.get_mandals(params[:term],1)
    mandal_names = []
    mandals.each do |man|
      mandal_names << man.name
    end
    render json: mandal_names
  end

end

app/helpers/mandals_helper.rb
module MandalsHelper
end

app/views/mandals/_form.html.erb
<%= form_for(@mandal) do |f| %>
  <% if @mandal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mandal.errors.count, "error") %> prohibited this mandal from being saved:</h2>

      <ul>
        <% @mandal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :name, :class => 'label-tag-style', :style => "text-transform: capitalize;color:black" %><br/>
        <%= f.text_field :name, :class => 'form-control', :placeholder => ' Name ', :required => true %>
      </div>
      <div class="form-group">
        <%= f.label :code, :class => 'label-tag-style', :style => "text-transform: capitalize;color:black" %><br/>
        <%= f.text_field :code, :class => 'form-control', :placeholder => ' code ', :required => true %>
      </div>
      <div class="field">
        <%= f.label :state_id %><br/>
        <%= f.select(:state_id, options_for_select(State.all.collect {|u| [u.name, u.id]}, @mandal.state_id), {:prompt => 'Select State'}, :required => "required", :class => 'form-control') %>
      </div>
      <div class="field">
        <%= f.label :district_id %><br/>
        <%= f.select(:district_id, options_for_select(District.all.collect {|u| [u.name, u.id]}, @mandal.district_id), {:prompt => 'Select District'}, :required => "required", :class => 'form-control') %>
      </div>
      <div class="field">
        <%= f.label :is_active %><br/>
        <%= f.check_box :is_active %>
      </div>
      <div class="actions">
        <%= f.submit(:class => 'btn btn-success btn-md') %>
      </div>
    </div>
  </div>
<% end %>

app/views/mandals/edit.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('Edit Mandal') %></div>

    <div class="col-sm-6 text-right"><%= link_to 'Back', mandals_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>

  <%= render 'form' %>
</div>

app/views/mandals/index.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('Mandals') %></div>
    <div class="col-sm-6 text-right"><%= link_to 'New Mandal', new_mandal_path, :class => 'btn btn-success', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>
  <table class="table table-bordered">
    <tr class="tr_style">
      <th>Name</th>
      <th>Code</th>
      <th>State</th>
      <th>District</th>
      <th>Is active</th>
      <th></th>
<!--      <th></th>-->
    </tr>

    <% @mandals.each do |mandal| %>
      <tr>
        <td><%= mandal.name %></td>
        <td><%= mandal.code %></td>
        <td><%= State.find_by_id(mandal.state_id).try(:name) %></td>
        <td><%= District.find_by_id(mandal.district_id).try(:name)%></td>
        <td><%= mandal.is_active %></td>
        <td><%= link_to 'Edit', edit_mandal_path(mandal) %></td>
<!--        <td><%#= link_to 'Destroy', mandal, method: :delete, data: {confirm: 'Are you sure?'} %></td>-->
      </tr>
    <% end %>
  </table>

  <br/>

</div>

app/views/mandals/new.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('New Mandal') %></div>

    <div class="col-sm-6 text-right"><%= link_to 'Back', mandals_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>

  <%= render 'form' %>
</div>