config/routes.rb
TAMC::Application.routes.draw do
  resources :system_settings do
    get :getAppVersion, :on => :collection
  end

  resources :cold_storages

  resources :gunnay_tare_weights

  resources :bag_names

  resources :sub_lots

  resources :market_charges

  resources :segments

  resources :gunny_details

  resources :sale_bill_components

  resources :salebills

  resources :bag_weights

  resources :weighment_bag_weights

  resources :bids

  resources :weighments do
    get :get_lot_details, :on => :collection
    get :create_weighment, :on => :collection
    post :update_weighment, :on => :collection
    get :edit_weighment, :on => :collection
    post :updated_weighment, :on => :collection
  end

  resources :lots do
    get :bidding_lots_list, :on => :collection
    get :add_bid, :on => :collection
    post :update_bid, :on => :collection
    get :close_bidding, :on => :collection
    get :show_entry_ticket, :on => :collection
    get :wayment_done_lots, :on => :collection
    get :make_inactive, :on => :collection
    get :takparty_receipt, :on => :collection
    get :update_data, :on => :collection
    get :modify_lot, :on => :collection
    get :modify_lot, :on => :collection
    post :lot_updated, :on => :collection
    get :lots_information, :on => :collection
    get :arrivedLotsInformation, :on => :collection
    get :pendingLotsInformation, :on => :collection
    get :returnedLotsInformation, :on => :collection
    get :day_wise_summary, :on => :collection
    get :day_wise_summary1, :on => :collection
    post :nrBidUpdate, :on => :collection
    post :nrBidUpdate1, :on => :collection
    get :nrlotBidding, :on => :collection
    get :nrlotBidding1, :on => :collection
    get :market_fee_details, :on => :collection
    get :makeDelete, :on => :collection
    get :add_remarks, :on => :collection
    post :save_remarks, :on => :collection
    get :detailsOfFee, :on => :collection
    get :getLotNumbers, :on => :collection
    get :getlotInformation, :on => :collection
  end

  resources :gate_entries do
    get :show_lots, :on => :collection
    get :create_gate_pass, :on => :collection
    post :generate_gate_entries, :on => :collection
    get :get_farmers, :on => :collection
    get :generate_gate_entry, :on => :collection
    get :set_farmer_details, :on => :collection
  end

  resources :farmers do
    post :list_of_vehicle_types, :on => :collection
    post :list_of_uoms, :on => :collection
    post :list_of_bag_types, :on => :collection
    post :list_of_commodities, :on => :collection
    post :list_of_farmer, :on => :collection

    post :stateList, :on => :collection
    post :districtsList, :on => :collection
    post :mandalsList, :on => :collection
    post :CityList, :on => :collection
    post :create_new_farmer, :on => :collection
    get :dashboard, :on => :collection
    get :dashboard1, :on => :collection
    get :amcwise_farmer_list, :on => :collection

  end

  resources :fee_components

  resources :fee_categories do
    get :listFeeCategoryForAutoSaleModel, :on => :collection
    get :listFeeComponentMstDtlAutoSaleModel, :on => :collection
  end

  resources :commodities

  resources :bag_types

  resources :unit_of_measurements

  resources :vehicle_types

  resources :users do
    get :create_user, :on => :collection
    post :update_user, :on => :collection
    get :agents_list, :on => :collection
    get :employee_list, :on => :collection
    get :create_agent, :on => :collection
    post :update_agent, :on => :collection
    get :create_employee, :on => :collection
    post :update_employee, :on => :collection
    post :user_verification, :on => :collection
    post :agentList, :on => :collection
    get :getMasterDataHW, :on => :collection
    get :cold_storages_update, :on => :collection
    get :getCaNames, :on => :collection
    get :inactive_user, :on => :collection
    get :active_user, :on => :collection
  end

  resources :user_roles

  resources :villages do
    get :mandal_wise_villages, :on => :collection
  end

  resources :mandals do
    get :districtwise_mandals_list, :on => :collection
  end

  resources :districts do
    get :statewise_district_list, :on => :collection
  end

  resources :states do

  end

  resources :amcs do
    get :all_amc_list, :on => :collection
    get :select_amc, :on => :collection
  end

  resources :user_sessions do
    get :new, :on => :collection
  end

  match 'logout', :controller => 'user_sessions', :action => 'destroy'
  match 'login', :controller => 'user_sessions', :action => 'new'

  root :to => 'user_sessions#new'

end

app/models/salebill.rb
class Salebill < ActiveRecord::Base
  attr_accessible :actual_weight, :agreement_type, :amc_id, :apx_weight, :bag_type_id, :commodity_id, :fee_category_id, :firm_name, :gross_amount, :lot_code, :lot_id, :net_amount, :net_payable, :net_weight, :no_of_bags, :rate_for_qui, :seller_id, :seller_type, :trader_id
end

app/controllers/salebills_controller.rb
class SalebillsController < ApplicationController
  # GET /salebills
  # GET /salebills.json
  def index
    @salebills = Salebill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @salebills }
    end
  end

  # GET /salebills/1
  # GET /salebills/1.json
  def show
    @salebill = Salebill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @salebill }
    end
  end

  # GET /salebills/new
  # GET /salebills/new.json
  def new
    @salebill = Salebill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @salebill }
    end
  end

  # GET /salebills/1/edit
  def edit
    @salebill = Salebill.find(params[:id])
  end

  # POST /salebills
  # POST /salebills.json
  def create
    @salebill = Salebill.new(params[:salebill])

    respond_to do |format|
      if @salebill.save
        format.html { redirect_to "/salebills", notice: 'Salebill was successfully created.' }
        format.json { render json: @salebill, status: :created, location: @salebill }
      else
        format.html { render action: "new" }
        format.json { render json: @salebill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salebills/1
  # PUT /salebills/1.json
  def update
    @salebill = Salebill.find(params[:id])

    respond_to do |format|
      if @salebill.update_attributes(params[:salebill])
        format.html { redirect_to "/salebills", notice: 'Salebill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @salebill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salebills/1
  # DELETE /salebills/1.json
  def destroy
    @salebill = Salebill.find(params[:id])
    @salebill.destroy

    respond_to do |format|
      format.html { redirect_to salebills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/salebills_helper.rb
module SalebillsHelper
end

app/views/salebills/_form.html.erb
<%= form_for(@salebill) do |f| %>
  <% if @salebill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salebill.errors.count, "error") %> prohibited this salebill from being saved:</h2>

      <ul>
        <% @salebill.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-4">

      <div class="field">
        <%= f.label :agreement_type %><br/>
        <%= f.text_field :agreement_type %>
      </div>
      <div class="field">
        <%= f.label :seller_type %><br/>
        <%= f.text_field :seller_type %>
      </div>
      <div class="field">
        <%= f.label :seller_id %><br/>
        <%= f.number_field :seller_id %>
      </div>
      <div class="field">
        <%= f.label :trader_id %><br/>
        <%= f.number_field :trader_id %>
      </div>
      <div class="field">
        <%= f.label :firm_name %><br/>
        <%= f.text_field :firm_name %>
      </div>
      <div class="field">
        <%= f.label :lot_code %><br/>
        <%= f.text_field :lot_code %>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="field">
        <%= f.label :commodity_id %><br/>
        <%= f.number_field :commodity_id %>
      </div>
      <div class="field">
        <%= f.label :apx_weight %><br/>
        <%= f.text_field :apx_weight %>
      </div>
      <div class="field">
        <%= f.label :rate_for_qui %><br/>
        <%= f.text_field :rate_for_qui %>
      </div>
      <div class="field">
        <%= f.label :net_weight %><br/>
        <%= f.text_field :net_weight %>
      </div>
      <div class="field">
        <%= f.label :actual_weight %><br/>
        <%= f.text_field :actual_weight %>
      </div>
      <div class="field">
        <%= f.label :fee_category_id %><br/>
        <%= f.number_field :fee_category_id %>
      </div>
    </div>
    <div class="col-sm-4">

      <div class="field">
        <%= f.label :bag_type_id %><br/>
        <%= f.number_field :bag_type_id %>
      </div>
      <div class="field">
        <%= f.label :no_of_bags %><br/>
        <%= f.number_field :no_of_bags %>
      </div>
      <div class="field">
        <%= f.label :net_amount %><br/>
        <%= f.text_field :net_amount %>
      </div>
      <div class="field">
        <%= f.label :gross_amount %><br/>
        <%= f.text_field :gross_amount %>
      </div>
      <div class="field">
        <%= f.label :net_payable %><br/>
        <%= f.text_field :net_payable %>
      </div>
      <div class="field">
        <%= f.label :amc_id %><br/>
        <%= f.number_field :amc_id %>
      </div>

    </div>
    <div class="actions">
      <%= f.submit(:class => 'btn btn-success btn-md') %>
    </div>
  </div>
<% end %>

app/views/salebills/edit.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('Edit Sale Bill') %></div>

    <div class="col-sm-6 text-right"><%= link_to 'Back', salebills_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>

  <%= render 'form' %>
</div>

app/views/salebills/index.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('Sale Bills') %></div>
    <div class="col-sm-6 text-right"><%= link_to 'New Sale Bill', new_salebill_path, :class => 'btn btn-success', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>
  <table class="table table-bordered">
    <tr class="tr_style">
      <th>Agreement type</th>
      <th>Seller type</th>
      <th>Seller</th>
      <th>Trader</th>
      <th>Firm name</th>
      <th>Lot code</th>
      <th>Commodity</th>
      <th>Apx weight</th>
      <th>Rate for qui</th>
      <th>Net weight</th>
      <th>Actual weight</th>
      <th>Fee category</th>
      <th>Bag type</th>
      <th>No of bags</th>
      <th>Net amount</th>
      <th>Gross amount</th>
      <th>Net payable</th>
      <th></th>
      <th></th>
    </tr>

    <% @salebills.each do |salebill| %>
      <tr>
        <td><%= salebill.agreement_type %></td>
        <td><%= salebill.seller_type %></td>
        <td><%= salebill.seller_id %></td>
        <td><%= salebill.trader_id %></td>
        <td><%= salebill.firm_name %></td>
        <td><%= salebill.lot_code %></td>
        <td><%= salebill.commodity_id %></td>
        <td><%= salebill.apx_weight %></td>
        <td><%= salebill.rate_for_qui %></td>
        <td><%= salebill.net_weight %></td>
        <td><%= salebill.actual_weight %></td>
        <td><%= salebill.fee_category_id %></td>
        <td><%= salebill.bag_type_id %></td>
        <td><%= salebill.no_of_bags %></td>
        <td><%= salebill.net_amount %></td>
        <td><%= salebill.gross_amount %></td>
        <td><%= salebill.net_payable %></td>
        <td><%= link_to 'Edit', edit_salebill_path(salebill) %></td>
        <td><%= link_to 'Destroy', salebill, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </table>

  <br/>
</div>

app/views/salebills/new.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('New Sale Bill') %></div>

    <div class="col-sm-6 text-right"><%= link_to 'Back', salebills_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>

  <%= render 'form' %>
</div>

app/views/salebills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Agreement type:</b>
  <%= @salebill.agreement_type %>
</p>

<p>
  <b>Seller type:</b>
  <%= @salebill.seller_type %>
</p>

<p>
  <b>Seller:</b>
  <%= @salebill.seller_id %>
</p>

<p>
  <b>Trader:</b>
  <%= @salebill.trader_id %>
</p>

<p>
  <b>Firm name:</b>
  <%= @salebill.firm_name %>
</p>

<p>
  <b>Lot:</b>
  <%= @salebill.lot_id %>
</p>

<p>
  <b>Lot code:</b>
  <%= @salebill.lot_code %>
</p>

<p>
  <b>Commodity:</b>
  <%= @salebill.commodity_id %>
</p>

<p>
  <b>Apx weight:</b>
  <%= @salebill.apx_weight %>
</p>

<p>
  <b>Rate for qui:</b>
  <%= @salebill.rate_for_qui %>
</p>

<p>
  <b>Net weight:</b>
  <%= @salebill.net_weight %>
</p>

<p>
  <b>Actual weight:</b>
  <%= @salebill.actual_weight %>
</p>

<p>
  <b>Fee category:</b>
  <%= @salebill.fee_category_id %>
</p>

<p>
  <b>Bag type:</b>
  <%= @salebill.bag_type_id %>
</p>

<p>
  <b>No of bags:</b>
  <%= @salebill.no_of_bags %>
</p>

<p>
  <b>Net amount:</b>
  <%= @salebill.net_amount %>
</p>

<p>
  <b>Gross amount:</b>
  <%= @salebill.gross_amount %>
</p>

<p>
  <b>Net payable:</b>
  <%= @salebill.net_payable %>
</p>

<p>
  <b>Amc:</b>
  <%= @salebill.amc_id %>
</p>


<%= link_to 'Edit', edit_salebill_path(@salebill) %> |
<%= link_to 'Back', salebills_path %>