config/routes.rb
TAMC::Application.routes.draw do
  resources :system_settings do
    get :getAppVersion, :on => :collection
  end

  resources :cold_storages

  resources :gunnay_tare_weights

  resources :bag_names

  resources :sub_lots

  resources :market_charges

  resources :segments

  resources :gunny_details

  resources :sale_bill_components

  resources :salebills

  resources :bag_weights

  resources :weighment_bag_weights

  resources :bids

  resources :weighments do
    get :get_lot_details, :on => :collection
    get :create_weighment, :on => :collection
    post :update_weighment, :on => :collection
    get :edit_weighment, :on => :collection
    post :updated_weighment, :on => :collection
  end

  resources :lots do
    get :bidding_lots_list, :on => :collection
    get :add_bid, :on => :collection
    post :update_bid, :on => :collection
    get :close_bidding, :on => :collection
    get :show_entry_ticket, :on => :collection
    get :wayment_done_lots, :on => :collection
    get :make_inactive, :on => :collection
    get :takparty_receipt, :on => :collection
    get :update_data, :on => :collection
    get :modify_lot, :on => :collection
    get :modify_lot, :on => :collection
    post :lot_updated, :on => :collection
    get :lots_information, :on => :collection
    get :arrivedLotsInformation, :on => :collection
    get :pendingLotsInformation, :on => :collection
    get :returnedLotsInformation, :on => :collection
    get :day_wise_summary, :on => :collection
    get :day_wise_summary1, :on => :collection
    post :nrBidUpdate, :on => :collection
    post :nrBidUpdate1, :on => :collection
    get :nrlotBidding, :on => :collection
    get :nrlotBidding1, :on => :collection
    get :market_fee_details, :on => :collection
    get :makeDelete, :on => :collection
    get :add_remarks, :on => :collection
    post :save_remarks, :on => :collection
    get :detailsOfFee, :on => :collection
    get :getLotNumbers, :on => :collection
    get :getlotInformation, :on => :collection
  end

  resources :gate_entries do
    get :show_lots, :on => :collection
    get :create_gate_pass, :on => :collection
    post :generate_gate_entries, :on => :collection
    get :get_farmers, :on => :collection
    get :generate_gate_entry, :on => :collection
    get :set_farmer_details, :on => :collection
  end

  resources :farmers do
    post :list_of_vehicle_types, :on => :collection
    post :list_of_uoms, :on => :collection
    post :list_of_bag_types, :on => :collection
    post :list_of_commodities, :on => :collection
    post :list_of_farmer, :on => :collection

    post :stateList, :on => :collection
    post :districtsList, :on => :collection
    post :mandalsList, :on => :collection
    post :CityList, :on => :collection
    post :create_new_farmer, :on => :collection
    get :dashboard, :on => :collection
    get :dashboard1, :on => :collection
    get :amcwise_farmer_list, :on => :collection

  end

  resources :fee_components

  resources :fee_categories do
    get :listFeeCategoryForAutoSaleModel, :on => :collection
    get :listFeeComponentMstDtlAutoSaleModel, :on => :collection
  end

  resources :commodities

  resources :bag_types

  resources :unit_of_measurements

  resources :vehicle_types

  resources :users do
    get :create_user, :on => :collection
    post :update_user, :on => :collection
    get :agents_list, :on => :collection
    get :employee_list, :on => :collection
    get :create_agent, :on => :collection
    post :update_agent, :on => :collection
    get :create_employee, :on => :collection
    post :update_employee, :on => :collection
    post :user_verification, :on => :collection
    post :agentList, :on => :collection
    get :getMasterDataHW, :on => :collection
    get :cold_storages_update, :on => :collection
    get :getCaNames, :on => :collection
    get :inactive_user, :on => :collection
    get :active_user, :on => :collection
  end

  resources :user_roles

  resources :villages do
    get :mandal_wise_villages, :on => :collection
  end

  resources :mandals do
    get :districtwise_mandals_list, :on => :collection
  end

  resources :districts do
    get :statewise_district_list, :on => :collection
  end

  resources :states do

  end

  resources :amcs do
    get :all_amc_list, :on => :collection
    get :select_amc, :on => :collection
  end

  resources :user_sessions do
    get :new, :on => :collection
  end

  match 'logout', :controller => 'user_sessions', :action => 'destroy'
  match 'login', :controller => 'user_sessions', :action => 'new'

  root :to => 'user_sessions#new'

end

app/models/segment.rb
class Segment < ActiveRecord::Base
  attr_accessible :amc_id, :is_active, :segment_name
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  # GET /segments
  # GET /segments.json
  def index

    if current_user.present? && current_user.amc_id.present?
      @segments = Segment.where("amc_id =?",current_user.amc_id)
    else
      @segments = Segment.all
    end



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @segments }
    end
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
    @segment = Segment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @segment }
    end
  end

  # GET /segments/new
  # GET /segments/new.json
  def new
    @segment = Segment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @segment }
    end
  end

  # GET /segments/1/edit
  def edit
    @segment = Segment.find(params[:id])
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(params[:segment])

    respond_to do |format|
      if @segment.save
        format.html { redirect_to '/segments', notice: 'Segment was successfully created.' }
        format.json { render json: @segment, status: :created, location: @segment }
      else
        format.html { render action: "new" }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /segments/1
  # PUT /segments/1.json
  def update
    @segment = Segment.find(params[:id])

    respond_to do |format|
      if @segment.update_attributes(params[:segment])
        format.html { redirect_to '/segments', notice: 'Segment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment = Segment.find(params[:id])
    @segment.destroy

    respond_to do |format|
      format.html { redirect_to segments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_for(@segment) do |f| %>
  <% if @segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
        <% @segment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <%= f.hidden_field :amc_id, :value => current_user.amc_id %>
      <div class="form-group">
        <%= f.label :segment_name, :class => 'label-tag-style', :style => "text-transform: capitalize;color:black" %>
        <%= f.text_field :segment_name, :class => 'form-control', :placeholder => ' Segment Name ', :required => true %>
      </div>
      <div class="form-group">
        <%= f.label :is_active %><br/>
        <%= f.check_box :is_active %>
      </div>
      <div class="actions">
        <%= f.submit(:class => 'btn btn-success btn-md') %>
      </div>
    </div>
  </div>
<% end %>

app/views/segments/edit.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('Edit Segment') %></div>

    <div class="col-sm-6 text-right"><%= link_to 'Back', segments_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>

  <%= render 'form' %>
</div>

app/views/segments/index.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('Segments') %></div>
    <div class="col-sm-6 text-right"><%= link_to 'New Segment', new_segment_path, :class => 'btn btn-success', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>
  <table class="table table-bordered">
    <tr class="tr_style">
      <th>Segment name</th>
      <th>Is active</th>
      <th></th>
      <th></th>
    </tr>

    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.segment_name %></td>
        <td><%= segment.is_active %></td>
        <td><%= link_to 'Edit', edit_segment_path(segment) %></td>
        <td><%= link_to 'Destroy', segment, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </table>

  <br/>
</div>

app/views/segments/new.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('New Segment') %></div>

    <div class="col-sm-6 text-right"><%= link_to 'Back', segments_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>

  <%= render 'form' %>
</div>